### ISSUE TITLE
How to use output?

### ISSUE THREAD

**Issue by mankoff** [simos/keyboardlayouteditor#21]
This looks like a great tool, but I'm not sure what to do with the output.

I'm trying to add some altGr accents to a US dvorak layout. The output of this tool is:

```
/////////////////////////////////////////////////////////////////////////////////
//
// Generated keyboard layout file with the Keyboard Layout Editor.
// For more about the software, see http://code.google.com/p/keyboardlayouteditor
//

xkb_symbols "var"
{
        name[Group1] = "mankoff_custom";
        include "us(dvorak)"
        key <AC01> { [       NoSymbol,       NoSymbol, dead_abovering, dead_abovering ] }; //   D˚ D˚
        key <AC02> { [       NoSymbol,       NoSymbol,  dead_abovedot,  dead_abovedot ] }; //   D˙ D˙
        key <AC03> { [       NoSymbol,       NoSymbol, dead_diaeresis, dead_diaeresis ] }; //   D¨ D¨
};
```

But what do I do with this file?

**Comment by hupfdule** [comment]
It's a keyboard layout file for X.
You need to put it into `/usr/share/X11/xkb/symbols/` (at least under Debian/Ubuntu), possibly with the filename `mankoff` and then load it with

    setxkbmap mankoff

**Comment by mankoff** [comment]
Thanks for reply. I've since solved this w/ hand-editing a custom file.
